export const editorSettings = {
  styleStrictMode: false,
  allowOverridingTokens: true,
  designTokensOptional: false,
  designTokens: {
    colors: [
      { name: 'Brand Red', value: 'var(--brand-red)' },
      { name: 'Brand White', value: 'var(--brand-white)' },
      { name: 'Brand Blue', value: 'var(--brand-blue)' },
      { name: 'Pastel Primary', value: 'var(--pastel-primary)' },
      { name: 'Pastel Secondary', value: 'var(--pastel-secondary)' },
      { name: 'Pastel Accent', value: 'var(--pastel-accent)' },
      { name: 'Pastel Success', value: 'var(--pastel-success)' },
      { name: 'Pastel Warning', value: 'var(--pastel-warning)' },
      { name: 'Pastel BG', value: 'var(--pastel-bg)' },
      { name: 'Pastel Text', value: 'var(--pastel-text)' },
      { name: 'Pastel Text Secondary', value: 'var(--pastel-text-secondary)' },
      { name: 'Primary', value: 'var(--primary, #E6C744)' },
      { name: 'Accent', value: 'var(--accent, #FFF5BF)' },
      { name: 'Secondary', value: 'var(--secondary, #C2C8DA)' },
      { name: 'Background', value: 'var(--background, #ffffff)' },
      { name: 'Background Light', value: 'var(--background-light, #e8e8e8)' },
      { name: 'Foreground', value: 'var(--foreground, #171717)' },
    ],
    fontFamily: [
      { name: 'Script', value: 'var(--font-script)' },
      { name: 'Brand', value: 'var(--font-brand)' },
      {
        name: 'Primary',
        value: 'Poppins, -apple-system, Roboto, Helvetica, sans-serif',
      },
      { name: 'Alternative', value: 'Arial, Helvetica, sans-serif' },
    ],
    fontSize: [
      { name: 'Hero Title', value: 'var(--font-size-hero-title)' },
      { name: 'Mega Menu Item', value: 'var(--font-size-mega-menu-item)' },
      { name: 'Beer Name', value: 'var(--font-size-beer-name)' },
      { name: 'Header Menu', value: 'var(--font-size-header-menu)' },
      { name: 'Hero Description', value: 'var(--font-size-hero-desc)' },
      { name: 'Largest', value: 'var(--size-xxlarge, 57px)' },
      { name: 'Larger', value: 'var(--size-xlarge, 46px)' },
      { name: 'Large', value: 'var(--size-large, 24px)' },
      { name: 'Medium', value: 'var(--size-medium, 18px)' },
      { name: 'Small', value: 'var(--size-small, 15px)' },
    ],
    lineHeight: [
      { name: 'Header', value: 'var(--line-height-header)' },
      { name: 'Mega Menu', value: 'var(--line-height-mega-menu)' },
      { name: 'Hero Title', value: 'var(--line-height-hero-title)' },
      { name: 'Base', value: 'var(--line-height-base)' },
    ],
    spacing: [
      { name: 'Header Padding', value: 'var(--spacing-header-padding)' },
      { name: 'Hero Padding', value: 'var(--spacing-hero-padding)' },
      { name: 'Hero Title Margin', value: 'var(--spacing-hero-title-margin)' },
      { name: 'Hero Desc Margin', value: 'var(--spacing-hero-desc-margin)' },
      { name: 'Mega Menu Padding', value: 'var(--spacing-mega-menu-padding)' },
      { name: 'Nav Padding', value: 'var(--spacing-nav-padding)' },
      { name: 'Nav Gap', value: 'var(--spacing-nav-gap)' },
      { name: 'Social Gap', value: 'var(--spacing-social-gap)' },
      { name: 'Menu Gap', value: 'var(--spacing-menu-gap)' },
      {
        name: 'Mega Menu Content Gap',
        value: 'var(--spacing-mega-menu-content-gap)',
      },
      {
        name: 'Beer Grid Container Padding',
        value: 'var(--spacing-beer-grid-container-padding)',
      },
      {
        name: 'Beer Grid Header Margin',
        value: 'var(--spacing-beer-grid-header-margin)',
      },
      { name: 'Beer Grid Gap', value: 'var(--spacing-beer-grid-gap)' },
      { name: 'Logo Offset', value: 'var(--spacing-logo-offset)' },
      { name: 'CTA Padding', value: 'var(--spacing-cta-padding)' },
      { name: 'XLarge', value: 'var(--space-xlarge, 46px)' },
      { name: 'Large', value: 'var(--space-large, 24px)' },
      { name: 'Medium', value: 'var(--space-medium, 18px)' },
      { name: 'Small', value: 'var(--space-small, 15px)' },
      { name: 'None', value: 'var(--space-none, 0px)' },
    ],
    sizing: [
      { name: 'Header Height', value: 'var(--size-header-height)' },
      { name: 'Hero Min Height', value: 'var(--size-hero-min-height)' },
      { name: 'Logo Width', value: 'var(--size-logo-width)' },
      { name: 'Icon Base', value: 'var(--size-icon-base)' },
      { name: 'Menu Bar Height', value: 'var(--size-menu-bar-height)' },
      { name: 'Menu Bar Width', value: 'var(--size-menu-bar-width)' },
    ],
    gap: [
      { name: 'XLarge', value: 'var(--space-xlarge, 46px)' },
      { name: 'Large', value: 'var(--space-large, 24px)' },
      { name: 'Medium', value: 'var(--space-medium, 18px)' },
      { name: 'Small', value: 'var(--space-small, 15px)' },
      { name: 'None', value: 'var(--space-none, 0px)' },
    ],
    borderRadius: [
      { name: 'CTA', value: 'var(--border-radius-cta)' },
      { name: 'Base', value: 'var(--border-radius-base)' },
      { name: 'Medium', value: 'var(--border-radius-medium, 10px)' },
      { name: 'None', value: 'var(--space-none, 0px)' },
    ],
    shadows: [
      { name: 'Header', value: 'var(--shadow-header)' },
      { name: 'CTA Hover', value: 'var(--shadow-cta-hover)' },
    ],
    transitions: [
      { name: 'Fast', value: 'var(--transition-fast)' },
      { name: 'Base', value: 'var(--transition-base)' },
    ],
    zIndices: [
      { name: 'Header', value: 'var(--z-index-header)' },
      { name: 'Overlay', value: 'var(--z-index-overlay)' },
    ],
  },
};
