export const editorSettings = {
  styleStrictMode: false,
  allowOverridingTokens: true,
  designTokensOptional: false,
  designTokens: {
    colors: [
      { name: 'Brand Red', value: 'var(--brand-red)' },
      { name: 'Brand White', value: 'var(--brand-white)' },
      { name: 'Brand Blue', value: 'var(--brand-blue)' },
      { name: 'Pastel Primary', value: 'var(--pastel-primary)' },
      { name: 'Pastel Secondary', value: 'var(--pastel-secondary)' },
      { name: 'Pastel Accent', value: 'var(--pastel-accent)' },
      { name: 'Pastel Success', value: 'var(--pastel-success)' },
      { name: 'Pastel Warning', value: 'var(--pastel-warning)' },
      { name: 'Pastel BG', value: 'var(--pastel-bg)' },
      { name: 'Pastel Text', value: 'var(--pastel-text)' },
      { name: 'Pastel Text Secondary', value: 'var(--pastel-text-secondary)' },
      { name: 'Primary', value: 'var(--primary, #E6C744)' },
      { name: 'Accent', value: 'var(--accent, #FFF5BF)' },
      { name: 'Secondary', value: 'var(--secondary, #C2C8DA)' },
      { name: 'Background', value: 'var(--background, #ffffff)' },
      { name: 'Background Light', value: 'var(--background-light, #e8e8e8)' },
      { name: 'Foreground', value: 'var(--foreground, #171717)' },
    ],
    fontFamily: [
      { name: 'Script', value: 'var(--font-script)' },
      { name: 'Brand', value: 'var(--font-brand)' },
      {
        name: 'Primary',
        value: 'Poppins, -apple-system, Roboto, Helvetica, sans-serif',
      },
      { name: 'Alternative', value: 'Arial, Helvetica, sans-serif' },
    ],
    fontSize: [
      { name: 'Largest', value: 'var(--size-xxlarge, 57px)' },
      { name: 'Larger', value: 'var(--size-xlarge, 46px)' },
      { name: 'Large', value: 'var(--size-large, 24px)' },
      { name: 'Medium', value: 'var(--size-medium, 18px)' },
      { name: 'Small', value: 'var(--size-small, 15px)' },
    ],
    spacing: [
      { name: 'XLarge', value: 'var(--space-xlarge, 46px)' },
      { name: 'Large', value: 'var(--space-large, 24px)' },
      { name: 'Medium', value: 'var(--space-medium, 18px)' },
      { name: 'Small', value: 'var(--space-small, 15px)' },
      { name: 'None', value: 'var(--space-none, 0px)' },
    ],
    gap: [
      { name: 'XLarge', value: 'var(--space-xlarge, 46px)' },
      { name: 'Large', value: 'var(--space-large, 24px)' },
      { name: 'Medium', value: 'var(--space-medium, 18px)' },
      { name: 'Small', value: 'var(--space-small, 15px)' },
      { name: 'None', value: 'var(--space-none, 0px)' },
    ],
    borderRadius: [
      { name: 'Medium', value: 'var(--border-radius-medium, 10px)' },
      { name: 'None', value: 'var(--space-none, 0px)' },
    ],
  },
};
